---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-petclinic-app
  labels:
    app: sample-petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-petclinic-app
  template:
    metadata:
      labels:
        app: sample-petclinic-app
    spec:
      containers:
      - name: sample-petclinic
        image: CHANGEME
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-petclinic-svc
  labels:
    app: sample-petclinic-svc
spec:
  type: ClusterIP
  selector:
    app: sample-petclinic-app
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-petclinic-ingress
spec:
  rules:
  - host: tekton-test-sample-petclinic.internal.k8slabhpe.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-petclinic-svc
            port:
              number: 8080
  ingressClassName: nginx
